version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: pms_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pms
    ports:
      - "5432:5432"
    volumes:
      - pms_data:/var/lib/postgresql/data

volumes:
  pms_data: